FROM postgres:latest

# Instalar PostGIS
RUN apt-get update \
    && apt-get install -y postgis postgresql-14-postgis-3 \
    && rm -rf /var/lib/apt/lists/*

# Criar extensão PostGIS no banco de dados
COPY ./init-postgis.sql /docker-entrypoint-initdb.d/
