
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xzowroybszlvbkgzurla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6b3dyb3lic3psdmJrZ3p1cmxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NDg1ODEsImV4cCI6MjA1NjQyNDU4MX0.Gl3tWTz5eQuSDtZ12YNBQa1V9sr4XkUmulHk7eTkBMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
