// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiywqroiovphdultgaet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppeXdxcm9pb3ZwaGR1bHRnYWV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2NzgwNTgsImV4cCI6MjA1NjI1NDA1OH0._auAk9bzk85D7BDy4OTEelHBHh68Z3xQ3Kn-BNoaE3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);